### PR TITLE
Updated converalls link and minor updates to README

### PR DESCRIPTION
**Pull request by acrlakshman**
Signed-off-by: Lakshman Anumolu <acrlakshman@gmail.com>

### CODE REVIEW

**Comment by 9prady9** [comment]
i will this open fr rest of the week, push any other changes you might have to this itself.

**Comment by acrlakshman** [comment]
Ok, looks like earlier link for coveralls was working, though it took time to update. Don't merge this pull, I shall remove the link edit I made and add new changes to the code and will push them into this commit...

**Comment by 9prady9** [comment]
@acrlakshman just force push the latest commit to remove that coveralls change. Yes, it takes time to update.

**Comment by 9prady9** [comment]
@acrlakshman what's the status on this ?

**Comment by acrlakshman** [comment]
I reverted back the updated link to the old link, the only minor change is the inclusion of license in readme... I didn't want to add OBJ write function into this commit and also wasn't sure whether to close this PR without merging, as the changes are trivial. I would say, we dont merge this commit, just close this PR. I will include the minor updates in my new commit which includes OBJ write function and introducing base class for geometry datastructures.

**Pull request closed without merging**
